import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import SidebarContext from "./context/SidebarContext";
import RouteContext from "./context/RouteContext";
import AOSProvider from "./context/AOS";
import Head from "next/head";
import { AuthProvider } from "./context/RoleContext";

const outfit = Outfit({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Moxtil FireDash",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/my-app/app/assets/icon.ico" />
        <title>Moxtil FireDash</title>
      </Head>
      <body className={`${outfit.className} antialiased`}>
        <ClerkProvider>
          <AuthProvider>
            <AOSProvider>
              <SidebarContext>
                <RouteContext>{children}</RouteContext>
              </SidebarContext>
            </AOSProvider>
          </AuthProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
